# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Kiko"
permalink:          /:year/:month/:day/:title.html

# URL
baseurl:            "/Kiko"
#baseurl:            "" #For Root Domain

# Navigation
nav:
  - name:           "About"
    href:           "//gfjaru.github.io/Kiko/about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Markdown
markdown:           rdiscount
